image:
  file: .gitpod.Dockerfile

tasks:
  - name: client
    before: cd client
    init: npm install
    command: npm start

  - name: server
    before: cd server
    init: npm install
    command: npm start
